version: "3"
services:

  nexus:
    image: sonatype/nexus3:latest
    environment:
      JAVA_MAX_MEM: "4g"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - ./data:/nexus-data
    ports:
      - 8081-8090:8081-8090
    restart: unless-stopped

networks:
  default:
    name: nexus-network
